name: 'Slack CLI Command Runner'
description: 'Execute Slack CLI commands in GitHub Actions'
inputs:
  command:
    description: "Slack CLI command to run"
    required: true
  verbose:
    description: "Enable verbose output"
    required: false
    default: 'false'
  automatic_installs:
    description: "Install latest CLI if not present"
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Slack CLI Command
      shell: bash
      env:
        SLACK_SERVICE_TOKEN: $SLACK_SERVICE_TOKEN
        SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
        VERBOSE: ${{ inputs.verbose }}
      run: |
        echo "Running command: ${{ inputs.command }}"
        echo "Verbose: ${{ inputs.verbose }}"
        if [ "${{ inputs.verbose }}" == "true" ]; then
          node parse-command.js ${{ inputs.command }} --verbose
        else
          node parse-command.js ${{ inputs.command }}
        fi