runs:
  using: composite
  steps:
    - name: Install Slack CLI
      uses: ./.github/.actions/slack-cli-installer/action.yml
      with:
        verbose: ${{ github.event.inputs.verbose }}
        automatic_installs: ${{ github.event.inputs.automatic_installs }}

    - name: Execute command via script
      if: ${{ github.event.inputs.command }}
      shell: bash
      env:
        SLACK_SERVICE_TOKEN: ${{ inputs.slack-service-token }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      run: | 
        echo "Running command: ${{ github.event.inputs.command }}"
        node src/parse-command.js ${{ github.event.inputs.command }}

    