runs:
  using: composite
  steps:
    - name: Install Slack CLI
      uses: ./.github/resources/.actions/slack-cli-installer
      with:
        verbose: ${{ inputs.verbose }}
        automatic_installs: ${{ inputs.automatic_installs }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run Slack CLI Command
      run: |
        echo "Running command: ${{ inputs.command }}"
        slack ${{ inputs.command }}
      shell: bash
      env:
        SLACK_SERVICE_TOKEN: $SLACK_SERVICE_TOKEN
        SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN



    