inputs:
  command:
    description: "Slack CLI command to run"
    required: true
  verbose:
    description: "Enable verbose output"
    default: true
  automatic_installs:
    description: "Install latest CLI if not present"
    default: true

runs:
  using: composite
  steps:
    - name: Install Slack CLI
      uses: ./.github/.actions/slack-cli-installer
      with:
        verbose: ${{ inputs.verbose }}
        automatic_installs: ${{ inputs.automatic_installs }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run Slack CLI Command
      run: |
        echo "Running command: ${{ inputs.command }}"
        slack ${{ inputs.command }}
      shell: bash
      env:
        SLACK_SERVICE_TOKEN: $SLACK_SERVICE_TOKEN
        SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN



    