runs:
  using: composite
  steps:
    - name: Execute command via script
      if: ${{ github.event.inputs.command }}
      shell: bash
      env:
        SLACK_SERVICE_TOKEN: ${{ inputs.slack-service-token }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      run: | 
        echo "Running command: ${{ github.event.inputs.command }}"
        node src/parse-command.js ${{ github.event.inputs.command }}

    - name: Run Slack CLI
      uses: ./.github/actions/slack-cli-runner
      with:
        verbose: false
        slack-service-token: ${{ secrets.SLACK_SERVICE_TOKEN }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
    