name: Slack CLI Installation
description: Download and cache the Slack CLI 

inputs:
  automatic_installs:
    description: "Install latest CLI if not present"
    required: false
    default: "3.6.0"

runs:
  using: composite
  steps:
    - name: Cache Slack CLI (automatic install)
      id: cache-cli-automatic
      uses: actions/cache@v4
      if: ${{ inputs.automatic_installs == '3.6.0'}}
      with:
        path: ~/.slack/bin
        #key: slack-cli-${{ runner.os }}-${{ runner.arch }}-latest
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ inputs.automatic_installs }}

    #- name: Cache Slack CLI (specific version)
      #id: cache-cli-specific
      #uses: actions/cache@v4
      #if: ${{ inputs.automatic_installs != '3.6.0' }} 
      #with:
        #path: ~/.slack/bin
        #key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ env.SLACK_CLI_VERSION }}

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH"

    - name: Add Slack CLI to PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin"

    - name: Install Slack CLI (Linux/macOS)
      if:
        (runner.os == 'Linux' || runner.os == 'macOS') && 
        (steps.cache-cli-automatic.outputs.cache-hit != 'true')
      shell: bash
      run:
        if [ "${{ inputs.automatic_installs }}" == '3.6.0' ]; then
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s
        else
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s 3.6.0
        fi

    #- name: Install Slack CLI (Windows)
      #if: 
        #runner.os == 'Windows' && 
        #(steps.cache-cli-automatic.outputs.cache-hit != 'true' && steps.cache-cli-specific.outputs.cache-hit != 'true')
      #shell: pwsh 
      #run: |
        #irm https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1 -OutFile 'install-windows-dev.ps1'
        #.\install-windows-dev.ps1 -Version $env:SLACK_CLI_VERSION || exit 0

