# Composite action that caches and installs CLI
name: Download Slack CLI
description: Install Slack CLI if needed and add to PATH
runs:
  using: composite
  steps:
    - name: Cache Slack CLI
      id: cache-cli
      uses: actions/cache@v4
      with:
        path: ~/.slack/bin
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ env.SLACK_CLI_VERSION }}  

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH"

    - name: Add Slack CLI to PATH (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin"

    - name: DEBUG: After Add to PATH (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: Write-Host "After Add to PATH"

      

    - name: Install Slack CLI (Linux/macOS)
      if:
        steps.cache-cli.outputs.cache-hit != 'true' && (runner.os == 'Linux' || runner.os == 'macOS')
      shell: bash
      run:
        curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v $SLACK_CLI_VERSION
    - name: Install Slack CLI (Windows)
      if: steps.cache-cli.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: powershell
      run: |
        irm https://downloads.slack-edge.com/slack-cli/install-windows.ps1 | iex

    - name: DEBUG: After CLI Install (Windows)
      if: steps.cache-cli.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: powershell
      run: Write-Host "After CLI Install"
