- name: Install Slack CLI (Windows)
  if: steps.cache-cli.outputs.cache-hit != 'true' && runner.os == 'Windows'
  shell: pwsh
  run: |
    Write-Host "🔧 Setting execution policy..."
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force

    Write-Host "🐍 PowerShell Language Mode: $($ExecutionContext.SessionState.LanguageMode)"

    $retryCount = 0
    $maxRetries = 3
    $success = $false

    while (-not $success -and $retryCount -lt $maxRetries) {
      try {
        Write-Host "📦 Installing Slack CLI (attempt $($retryCount + 1))..."
        
        & {
          irm https://downloads.slack-edge.com/slack-cli/install-windows.ps1 | iex
        }

        $success = $true
        Write-Host "✅ Slack CLI installation complete."
      } catch {
        $retryCount++
        Write-Host "⚠️ Installation failed (attempt $retryCount). Retrying in 5 seconds..."
        Start-Sleep -Seconds 5
      }
    }

    if (-not $success) {
      throw "❌ Failed to install Slack CLI after $maxRetries attempts."
    }

    Write-Host "🛣️ PATH after install:"
    Write-Host $env:PATH

    # 👇 Force exit the step in case something is hanging
    exit 0
