name: Download Slack CLI
description: Install and cache Slack CLI 
runs:
  using: composite
  steps:
    - name: Cache Slack CLI
      id: cache-cli
      uses: actions/cache@v4
      with:
        path: ~/.slack/bin
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ env.SLACK_CLI_VERSION }}  

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH"

    # - name: Add Slack CLI to PATH (Windows)
    #   if: runner.os == 'Windows'
    #   shell: pwsh
    #   run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin"

    - name: Install Slack CLI (Linux/macOS)
      if:
        steps.cache-cli.outputs.cache-hit != 'true' && (runner.os == 'Linux' || runner.os == 'macOS')
      shell: bash
      run:
        curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v $SLACK_CLI_VERSION

    - name: Install Deno (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        iwr https://deno.land/install.ps1 -useb | iex
        echo "$env:USERPROFILE\.deno\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Install Slack CLI (Windows)
      # steps.cache-cli.outputs.cache-hit != 'true' &&
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ExecutionContext.SessionState.LanguageMode = "FullLanguage"
        Write-Host "PowerShell Language Mode set to $($ExecutionContext.SessionState.LanguageMode)" 
        irm https://downloads.slack-edge.com/slack-cli/install-windows.ps1 | iex
