name: Slack CLI Installation
description: Download and cache the Slack CLI 
runs:
  using: composite
  steps:
    - name: Cache Slack CLI
      id: cache-cli
      uses: actions/cache@v4
      with:
        path: ~/.slack/bin
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ env.SLACK_CLI_VERSION }}  

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH"

    - name: Add Slack CLI to PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin"

    - name: Install Slack CLI (Linux/macOS)
      if:
        (runner.os == 'Linux' || runner.os == 'macOS') && steps.cache-cli.outputs.cache-hit != 'true' 
      shell: bash
      run:
        curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v $SLACK_CLI_VERSION

    - name: Install Slack CLI (Windows)
      if: runner.os == 'Windows' && steps.cache-cli.outputs.cache-hit != 'true'
      shell: pwsh 
      run: |
        irm https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1 -OutFile 'install-windows-dev.ps1'
        .\install-windows-dev.ps1 -Version $env:SLACK_CLI_VERSION || exit 0


        


  slack_bot_token:
    description: 'Slack Bot Token'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Slack CLI
      if: ${{ inputs.automatic_installs == 'true' }}
      shell: bash
      run: |
        if [ "${{ inputs.verbose }}" == 'true' ]; then
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v ${{ env.SLACK_CLI_VERSION || 'latest' }}
        else
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- ${{ env.SLACK_CLI_VERSION || 'latest' }}
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Execute command via script
      shell: bash
      run: |
        echo "Running command: ${{ inputs.command }}"
        node src/parse-command.js ${{ inputs.command }}
      env:
        SLACK_SERVICE_TOKEN: ${{ inputs.slack_service_token }}
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        GITHUB_ACTIONS: true
