# Execute command
name: GCli project wip script 

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'XX'
        required: true

jobs:
  deploy:
    name: "XX"
    runs-on: ${{ matrix.os }}
    env: 
      SLACK_CLI_VERSION: "3.5.2"
    timeout-minutes: 5

  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Slack CLI
        uses: ./.github/actions/deploy-slack-app
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install shell-quote

      - name: Execute command via script
        if: always()
        run: | 
            echo "Running command: ${{ github.event.inputs.command }}"
            node parse-command.js ${{ github.event.inputs.command }}
        env:
          SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }} 
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
