name: Slack CLI Command Runner

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Slack CLI command to run'
        required: true

jobs:
  deploy:
    name: "Run Slack CLI command"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #ubuntu-latest, macos-latest, 
        os: [windows-latest]
        node: [16, 18, 20, 22, 24]
    env: 
      SLACK_CLI_VERSION: "3.5.2"
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Slack CLI
        uses: ./.github/actions/deploy-slack-app
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}


        
