# GitHub Actions workflow that automatically deploys Slack app whenever code is pushed to main

name: (Re)Deploy Slack app on push to main 

on:
  push:
    branches: [ main ] # master??

jobs:
  deploy:
    name: 'Deploy Slack app using CLI'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy a Slack app
      uses: slackapi/slack-github-action@v2.0.0
      with:
        command: slack deploy --app ${{ secrets.SLACK_APP_ID }}
        token: ${{ secrets.SLACK_SERVICE_TOKEN }}