# Deploy Slack app on push to main
name: (Re)Deploy Slack app on push to main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 'Deploy Slack app using CLI'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy a Slack app
      uses: slackapi/slack-github-action@v2.0.0
      with:
        command: slack deploy --app ${{ secrets.SLACK_APP_ID }}
        method: cli
        token: ${{ secrets.SLACK_SERVICE_TOKEN }}