name: E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-slack-cli:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: slack auth login
        id: auth
        uses: ./.github/.actions/test-action
        with:
          command: "auth list"
          cli_version: "latest"

      - name: slack login
        id: login
        uses: ./.github/.actions/test-action
        with:
          command: "login"
          cli_version: "latest"

      - name: debug outputs
        run: |
          echo "stdout: '${{ steps.auth.outputs.stdout }}'"
          echo "success: '${{ steps.auth.outputs.success }}'"
          echo "command executed: '${{ steps.auth.outputs.command_executed }}'"
          echo "stdout: '${{ steps.login.outputs.stdout }}'"
          echo "success: '${{ steps.login.outputs.success }}'"
          echo "command executed: '${{ steps.login.outputs.command_executed }}'"

      - name: failure
        if: steps.auth.outputs.success != 'true' || steps.login.outputs.success
        run: |
          echo "failure"
          echo "stdout: ${{ steps.auth.outputs.stdout }}"
          exit 1