name: Integration Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-basic-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run slack version
        id: version
        uses: ./.github/.actions/test-action
        with:
          command: "version"
          cli_version: "3.6.0"

      - name: Debug outputs
        run: |
          echo "=== OUTPUT DEBUG ==="
          echo "STDOUT: '${{ steps.version.outputs.stdout }}'"
          echo "Success: '${{ steps.version.outputs.success }}'"
          echo "Exit Code: '${{ steps.version.outputs.exit_code }}'"
          echo "Command Executed: '${{ steps.version.outputs.command_executed }}'"
          echo "===================="

      - name: Verify CLI version
        run: |
          if [ "${{ steps.version.outputs.success }}" != "true" ]; then
            echo "❌ CLI version command failed"
            echo "Exit code: ${{ steps.version.outputs.exit_code }}"
            echo "Output: ${{ steps.version.outputs.stdout }}"
            exit 1
          else
            echo "✅ CLI version command succeeded"
            echo "Output: ${{ steps.version.outputs.stdout }}"
          fi