jobs:
  test-basic-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run slack version
        id: version
        uses: ./.github/.actions/test-action
        with:
          command: "version"
          cli_version: "3.6.0"
        env:
          SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Debug outputs
        run: |
          echo "STDOUT: ${{ steps.version.outputs.stdout }}"
          echo "Success: ${{ steps.version.outputs.success }}"
          echo "Exit Code: ${{ steps.version.outputs.exit_code }}"
          echo "Command Executed: ${{ steps.version.outputs.command_executed }}"

      - name: Verify CLI version
        run: |
          if [ "${{ steps.version.outputs.success }}" != "true" ]; then
            echo "CLI version failure"
            exit 1
          fi
