- name: Run Slack CLI Command (with capture)
  id: run-slack-cli-command
  shell: bash
  run: |
    set +e
    output=$(slack ${{ inputs.command }} --skip-update 2>&1)
    exit_code=$?
    set -e

    echo "stdout<<EOF" >> $GITHUB_OUTPUT
    echo "$output" >> $GITHUB_OUTPUT
    echo "EOF" >> $GITHUB_OUTPUT

    # Capture exit code and command executed
    echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
    echo "command_executed=slack ${{ inputs.command }}" >> $GITHUB_OUTPUT

    if [ $exit_code -eq 0 ]; then
      echo "success=true" >> $GITHUB_OUTPUT
    else
      echo "success=false" >> $GITHUB_OUTPUT
    fi
